pipeline {
	agent any

	stages {
		stage('Build Docker Image') {
			steps {
				sh 'docker build -t reg.phy0.in/chota .'
			}
		}

		stage('Push the Docker Image to reg.phy0.in') {
			steps {
				sh 'docker push reg.phy0.in/chota'
			}
		}

		stage('Deploy deployment and service file') {
			steps {
			    withKubeCredentials(kubectlCredentials: [[caCertificate: '', clusterName: 'default', contextName: 'default', credentialsId: 'k3s-token', namespace: '', serverUrl: 'https://k8s.phy0.in']]) {
    				sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'  
                    sh 'chmod u+x ./kubectl'
    				sh './kubectl apply -f deploy/kubernetes.yml'
                }
			}
		}
	}
}
