apiVersion: apps/v1
kind: Deployment
metadata:
    name: chota
spec:
    replicas: 3
    selector:
        matchLabels:
            app: chota-api
    template:
        metadata:
            labels:
                app: chota-api
        spec:
            containers:
                - name: chota
                  image: reg.phy0.in/chota:latest
                  imagePullPolicy: 'Always'
                  ports:
                      - containerPort: 8080
                        name: api-port
                  env:
                      - name: DATABASE_URL
                        value: 'postgres://chota:password@chota-db-service/chota?sslmode=disable'
                      - name: STORAGE_MODE
                        value: 'postgres'
                      - name: BIND_ADDRESS
                        value: '0.0.0.0'
---
apiVersion: v1
kind: Service
metadata:
    name: chota-api-service
spec:
    selector:
        app: chota-api
    ports:
        - protocol: TCP
          port: 4000
          targetPort: api-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: chota-ingress
spec:
    tls:
        - secretName: phy0-in
    rules:
        - host: s.phy0.in
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: chota-api-service
                            port:
                                number: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: chota-db
spec:
    replicas: 1
    selector:
        matchLabels:
            app: chota-db
    template:
        metadata:
            labels:
                app: chota-db
        spec:
            containers:
                - name: chota-db
                  image: postgres:latest
                  ports:
                      - containerPort: 5432
                        name: db-port
                  env:
                      - name: POSTGRES_USER
                        value: 'chota'
                      - name: POSTGRES_PASSWORD
                        value: 'password'
                      - name: POSTGRES_DB
                        value: 'chota'
---
apiVersion: v1
kind: Service
metadata:
    name: chota-db-service
spec:
    selector:
        app: chota-db
    ports:
        - protocol: TCP
          port: 5432
          targetPort: db-port
