apiVersion: apps/v1
kind: Deployment
metadata:
    name: short
spec:
    replicas: 3
    selector:
        matchLabels:
            app: short-api
    template:
        metadata:
            labels:
                app: short-api
        spec:
            containers:
                - name: short
                  image: reg.phy0.in/short:latest
                  imagePullPolicy: 'Always'
                  ports:
                      - containerPort: 8080
                        name: api-port
                  env:
                      - name: DATABASE_URL
                        value: 'postgres://short:password@short-db-service/short?sslmode=disable'
                      - name: STORAGE_MODE
                        value: 'postgres'
                      - name: BIND_ADDRESS
                        value: '0.0.0.0'
---
apiVersion: v1
kind: Service
metadata:
    name: short-api-service
spec:
    type: LoadBalancer
    selector:
        app: short-api
    ports:
        - protocol: TCP
          port: 80
          targetPort: api-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: short-db
spec:
    replicas: 1
    selector:
        matchLabels:
            app: short-db
    template:
        metadata:
            labels:
                app: short-db
        spec:
            containers:
                - name: short-db
                  image: postgres:latest
                  ports:
                      - containerPort: 5432
                        name: db-port
                  env:
                      - name: POSTGRES_USER
                        value: 'short'
                      - name: POSTGRES_PASSWORD
                        value: 'password'
                      - name: POSTGRES_DB
                        value: 'short'
---
apiVersion: v1
kind: Service
metadata:
    name: short-db-service
spec:
    selector:
        app: short-db
    ports:
        - protocol: TCP
          port: 5432
          targetPort: db-port
